###
// get all data
GET http://localhost:5000/users

###
// get single user
GET http://localhost:5000/users/2b27b128-3525-420a-ae13-35814857c6a1

### 
//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "agung",
    "username": "agungp",
    "email": "agung@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

### //update user
PATCH  http://localhost:5000/users/c8b5f898-8db7-4960-afdd-2496341548c7
Content-Type: application/json

{
    "name": "agung akwokaw",
    "username":"agungn",
    "email": "agung@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}

###
// delete user
DELETE http://localhost:5000/users/f8ef9bcb-e186-4c03-a889-d8a7efd443dd

###
// login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "agungn",
    "password": "123456"
}

###
// halobang, cek jika sudah login atau belum
GET http://localhost:5000/halo
