###
// get all data
GET http://localhost:5000/users

###
// get single user
GET http://localhost:5000/users/52359d1f-4593-46a4-b085-5d03deb188f0

### 
//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "client",
    "username": "ngeteh",
    "email": "ngeteh@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "asisten"
}

### //update user
PATCH  http://localhost:5000/users/27cfd26c-af9c-46d2-aed1-21d18be0670d
Content-Type: application/json

{
    "name": "clientsss",
    "username": "ngeteh",
    "email": "ngeteh@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}

###
// delete user
DELETE http://localhost:5000/users/27cfd26c-af9c-46d2-aed1-21d18be0670d

###
// login instruktur
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "fajarspace",
    "password": "123456"
}

###
// login asisten
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "agungn",
    "password": "123456"
}

###
// halobang, cek jika sudah login atau belum
GET http://localhost:5000/halo

###
// logout
DELETE http://localhost:5000/logout


###
// get all jadwals
GET http://localhost:5000/jadwals

### // post data jadwal
POST http://localhost:5000/jadwals
Content-Type: application/json

{
    "asisten" : "romdon",
    "hari" : "sabtu",
    "kelas" : "ti 20 a 3",
    "waktu" : "jam 10"

}